---
- name: Preflight tasks
  ansible.builtin.import_tasks: preflight.yml
  tags:
    - openvpn_exporter_install
    - openvpn_exporter

- name: Installation tasks
  ansible.builtin.import_tasks: install.yml
  become: True
  tags:
    - openvpn_exporter_install
    - openvpn_exporter

- name: Ensure openvpn_exporter service is started and enabled
  become: True
  ansible.builtin.systemd:
    daemon_reload: True
    name: openvpn_exporter
    state: started
    enabled: True
  tags:
    - openvpn_exporter_run
    - openvpn_exporter
